"use client";
import { useState } from "react";
import type { UserProfile } from "../../lib/auth/profile";

type CleanupPreview = { donors: number; gifts: number; interactions: number; recommendations: number };
type VerificationPreview = { records: number; donors: number; fingerprints: number; imports: number };

export function SettingsExperience({ initialProfile }: { initialProfile: UserProfile }) {
  const [profile, setProfile] = useState(initialProfile);
  const [status, setStatus] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const [message, setMessage] = useState("");
  const [cleanup, setCleanup] = useState<CleanupPreview | null>(null);
  const [confirmation, setConfirmation] = useState("");
  const [backedUp, setBackedUp] = useState(false);
  const [verification, setVerification] = useState<VerificationPreview | null>(null);
  const [verificationConfirmation, setVerificationConfirmation] = useState("");
  const [verificationBackedUp, setVerificationBackedUp] = useState(false);
  const [reviewModeStatus, setReviewModeStatus] = useState<"idle" | "saving" | "saved" | "error">("idle");

  async function save(event: React.FormEvent) { event.preventDefault(); setStatus("saving"); const response = await fetch("/api/profile", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(profile) }); const body = await response.json(); if (!response.ok) { setMessage(body.error || "Profile could not be saved"); setStatus("error"); } else { setProfile(body); setMessage("Profile saved."); setStatus("saved"); } }
  async function previewCleanup() { const response = await fetch("/api/sample-data"); const body = await response.json(); if (!response.ok) { setMessage(body.error); setStatus("error"); } else setCleanup(body); }
  async function removeSamples() { const response = await fetch("/api/sample-data", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmation, backupConfirmed: backedUp }) }); const body = await response.json(); if (!response.ok) { setMessage(body.error); setStatus("error"); } else { setCleanup({ donors: 0, gifts: 0, interactions: 0, recommendations: 0 }); setMessage(`Sample cleanup completed. Audit ${body.auditId}.`); setStatus("saved"); } }
  async function previewVerification() { const response = await fetch("/api/verification-data"); const body = await response.json(); if (!response.ok) { setMessage(body.error); setStatus("error"); } else setVerification(body); }
  async function removeVerification() { const response = await fetch("/api/verification-data", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmation: verificationConfirmation, backupConfirmed: verificationBackedUp }) }); const body = await response.json(); if (!response.ok) { setMessage(body.error); setStatus("error"); } else { setVerification({ records: 0, donors: 0, fingerprints: 0, imports: 0 }); setMessage(`Verification cleanup completed. Audit ${body.auditId}.`); setStatus("saved"); } }
  async function saveReviewMode() { setReviewModeStatus("saving"); const response = await fetch("/api/profile", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ importReviewMode: profile.importReviewMode }) }); const body = await response.json(); if (!response.ok) { setMessage(body.error || "Import review mode could not be saved"); setReviewModeStatus("error"); } else { setProfile(body); setMessage("Import review mode saved."); setReviewModeStatus("saved"); } }
  const field = (key: keyof UserProfile, label: string, required = false, type = "text") => <label>{label}<input type={type} required={required} value={profile[key]} onChange={(event) => setProfile({ ...profile, [key]: event.target.value })} /></label>;

  return <>
    <section className="support-card import-review-settings"><h2>Import Review Mode</h2><p>Choose how much confirmation you want when a JL household already exists. Local overrides and possible duplicates always require attention.</p><fieldset><legend>When JL Code matches an existing donor</legend>{[
      ["review_every", "Review every existing donor", "Pause on every match, including donors with no changes."],
      ["changes_only", "Review only donors with changes", "Continue unchanged donors and review every changed donor."],
      ["auto_unchanged", "Auto-continue unchanged donors", "Fastest: unchanged donors continue automatically; changed donors still require review."],
    ].map(([value, label, description]) => <label key={value} className={profile.importReviewMode === value ? "selected" : ""}><input type="radio" name="importReviewMode" value={value} checked={profile.importReviewMode === value} onChange={() => { setProfile({ ...profile, importReviewMode: value as UserProfile["importReviewMode"] }); setReviewModeStatus("idle"); }} /><span><strong>{label}</strong><small>{description}</small></span></label>)}</fieldset><button type="button" onClick={saveReviewMode} disabled={reviewModeStatus === "saving"}>{reviewModeStatus === "saving" ? "Saving…" : "Save import review mode"}</button>{reviewModeStatus === "saved" && <small role="status">Saved for your account and future sign-ins.</small>}</section>
    <section className="support-card"><h2>Your profile</h2><p>Fundraising OS uses this identity for greetings, dates, briefs, and your private workspace.</p><form className="profile-form" onSubmit={save}>{field("fullName", "Full name", true)}{field("preferredFirstName", "Preferred first name", true)}{field("organizationName", "Organization name", true)}{field("jobTitle", "Job title (optional)")}<label>Email<input value={profile.email} disabled /></label><label>Timezone<select value={profile.timezone} onChange={(event) => setProfile({ ...profile, timezone: event.target.value })}><option>America/New_York</option><option>America/Chicago</option><option>America/Denver</option><option>America/Los_Angeles</option><option>America/Phoenix</option><option>Europe/London</option><option>Asia/Jerusalem</option></select></label>{field("avatarUrl", "Profile photo HTTPS URL (optional)", false, "url")}<button type="submit" disabled={status === "saving"}>{status === "saving" ? "Saving…" : "Save profile"}</button></form></section>
    <section className="support-card"><h2>Sample data cleanup</h2><p>Live workspace mode already excludes sample records. This optional owner-only action permanently removes sample records after a preview and backup.</p>{!cleanup ? <button onClick={previewCleanup}>Preview sample cleanup</button> : <div><p><strong>{cleanup.donors}</strong> sample donors, <strong>{cleanup.gifts}</strong> gifts, <strong>{cleanup.interactions}</strong> interactions, and <strong>{cleanup.recommendations}</strong> reminders would be removed.</p>{cleanup.donors > 0 && <><a href="/api/import/backup" onClick={() => setBackedUp(true)}>Download backup first</a><label className="cleanup-confirm"><input type="checkbox" checked={backedUp} onChange={(event) => setBackedUp(event.target.checked)} /> I downloaded the backup</label><label>Type REMOVE SAMPLE DATA<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><button className="danger-button" onClick={removeSamples} disabled={!backedUp || confirmation !== "REMOVE SAMPLE DATA"}>Remove sample records</button></>}</div>}</section>
    <section className="support-card"><h2>Verification data cleanup</h2><p>Preview and remove only records carrying the dedicated verification origin and campaign marker.</p>{!verification ? <button onClick={previewVerification}>Preview verification cleanup</button> : <div><p><strong>{verification.records}</strong> verification giving records across <strong>{verification.donors}</strong> donors would be removed. <strong>{verification.imports}</strong> associated verification imports would also be removed.</p>{verification.records > 0 && <><a href="/api/import/backup" onClick={() => setVerificationBackedUp(true)}>Download fresh backup first</a><label className="cleanup-confirm"><input type="checkbox" checked={verificationBackedUp} onChange={(event) => setVerificationBackedUp(event.target.checked)} /> I downloaded the fresh backup</label><label>Type REMOVE VERIFICATION DATA<input value={verificationConfirmation} onChange={(event) => setVerificationConfirmation(event.target.value)} /></label><button className="danger-button" onClick={removeVerification} disabled={!verificationBackedUp || verificationConfirmation !== "REMOVE VERIFICATION DATA"}>Remove verification records</button></>}</div>}</section>
    {message && <p className={status === "error" ? "capture-error" : "capture-assurance"} role={status === "error" ? "alert" : "status"}>{message}</p>}
  </>;
}
