import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { env } from "cloudflare:workers";
import { AppShell } from "../../components/AppShell";
import { requireChatGPTUser } from "../../chatgpt-auth";
import { ensureUserProfile } from "../../../lib/auth/profile";
import { getDataMode } from "../../../lib/workspace/mode";
import { DONOR_GIVING_SQL } from "../../../lib/relationships/giving";
import { isScheduledActivity, sanitizeScheduledRelationshipContext } from "../../../lib/workspace/scheduled-activity";

export const metadata: Metadata = { title: "Donor relationship" };
export const dynamic = "force-dynamic";
type Donor = { id: string; display_name: string; donor_code: string | null; email: string | null; phone: string | null; home_phone: string | null; address_line_1: string | null; city: string | null; state: string | null; postal_code: string | null; country: string | null; primary_first_name: string | null; spouse_first_name: string | null; primary_title: string | null; spouse_title: string | null; external_id: string | null; relationship_summary: string | null; institutional_memory: string | null };
type Activity = { id: string; activity_date: number | null; committed_cents: number | null; paid_cents: number | null; balance_cents: number | null; item_type: string | null; description: string | null; category: string };
type Gift = { id: string; received_at: number; amount_cents: number; fund: string };
type Interaction = { id: string; type: string; occurred_at: number; summary: string; source: string; created_at: number };
type Recommendation = { id: string; action: string; reason: string; due_at: number | null };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100);
const date = (epoch: number, timezone: string) => new Intl.DateTimeFormat("en-US", { timeZone: timezone, month: "short", day: "numeric", year: "numeric" }).format(new Date(epoch * 1000));
const dateTime = (epoch: number, timezone: string) => new Intl.DateTimeFormat("en-US", { timeZone: timezone, month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(epoch * 1000));

export default async function DonorPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const identity = await requireChatGPTUser(`/donors/${encodeURIComponent(id)}`);
  const profile = await ensureUserProfile(identity);
  const mode = await getDataMode(profile.id);
  const donor = await env.DB.prepare(`SELECT id, display_name, donor_code, email, phone, home_phone, address_line_1, city, state, postal_code, country, primary_first_name, spouse_first_name, primary_title, spouse_title, external_id, relationship_summary, institutional_memory FROM donors WHERE id = ? AND ${mode === "demo" ? "data_source = 'sample'" : "owner_user_id = ? AND data_source = 'live'"} LIMIT 1`).bind(...(mode === "demo" ? [id] : [id, profile.id])).first<Donor>();
  if (!donor) notFound();
  const [activityResult, giftResult, interactionResult, recommendationResult] = await Promise.all([
    (mode === "demo" ? env.DB.prepare("SELECT id, activity_date, committed_cents, paid_cents, balance_cents, item_type, description, category FROM giving_activities WHERE donor_id = ? AND record_origin = 'sample' AND category NOT IN ('needs_review','nonfinancial_entry') ORDER BY activity_date DESC LIMIT 500").bind(id) : env.DB.prepare(DONOR_GIVING_SQL).bind(id, profile.id)).all<Activity>(),
    env.DB.prepare("SELECT id, received_at, amount_cents, fund FROM gifts WHERE donor_id = ? ORDER BY received_at DESC LIMIT 500").bind(id).all<Gift>(),
    env.DB.prepare(`SELECT id, type, occurred_at, summary, source, created_at FROM interactions WHERE donor_id = ? ${mode === "demo" ? "" : "AND user_id = ?"} ORDER BY occurred_at DESC LIMIT 200`).bind(...(mode === "demo" ? [id] : [id, profile.id])).all<Interaction>(),
    env.DB.prepare(`SELECT id, action, reason, due_at FROM recommendations WHERE donor_id = ? ${mode === "demo" ? "" : "AND user_id = ?"} AND status = 'open' ORDER BY due_at LIMIT 20`).bind(...(mode === "demo" ? [id] : [id, profile.id])).all<Recommendation>(),
  ]);
  const activities = activityResult.results;
  const legacyGifts = giftResult.results;
  const paid = activities.reduce((sum, item) => sum + (item.paid_cents ?? 0), 0) + legacyGifts.reduce((sum, item) => sum + item.amount_cents, 0);
  const open = activities.reduce((sum, item) => sum + Math.max(0, item.balance_cents ?? 0), 0);
  const mostRecent = activities.find((item) => (item.paid_cents ?? 0) > 0);
  const people = [donor.primary_first_name && `${donor.primary_title ? `${donor.primary_title} ` : ""}${donor.primary_first_name}`, donor.spouse_first_name && `${donor.spouse_title ? `${donor.spouse_title} ` : ""}${donor.spouse_first_name}`].filter(Boolean).join(" & ");
  const address = [donor.address_line_1, [donor.city, donor.state, donor.postal_code].filter(Boolean).join(" "), donor.country].filter(Boolean);
  const next = recommendationResult.results[0];
  const completedInteractions = interactionResult.results.filter((item) => !isScheduledActivity(item.source, item.occurred_at, item.created_at));
  const relationshipContext = sanitizeScheduledRelationshipContext(donor.relationship_summary, donor.institutional_memory, interactionResult.results.map((item) => ({ type: item.type, summary: item.summary, source: item.source, occurredAt: item.occurred_at, createdAt: item.created_at })));
  return <AppShell active="donors"><div className="donor-breadcrumb"><a href="/">Today</a><span>/</span><a href="/donors">Donors</a><span>/</span><strong>{donor.donor_code || donor.external_id || "Relationship"}</strong></div>
    <header className="donor-header"><div className="donor-identity"><div className="avatar donor-avatar">{donor.display_name.slice(0, 2).toUpperCase()}</div><div><div className="identity-line"><h1>{donor.display_name}</h1>{mode === "demo" && <span className="relationship-badge">Demo record</span>}</div>{people && <p>{people}</p>}<div className="contact-row">{donor.email && <a href={`mailto:${donor.email}`}>✉ {donor.email}</a>}{donor.phone && <a href={`tel:${donor.phone.replace(/\D/g, "")}`}>☎ {donor.phone}</a>}</div></div></div>{mode === "live" && <div className="header-actions"><a href={`/capture?donorId=${encodeURIComponent(id)}`}>＋ Log interaction</a></div>}</header>
    {mode === "live" && <nav className="meeting-brief-entry" aria-label="Meeting preparation"><div><strong>Meeting coming up?</strong><span>Review a concise brief built only from this donor’s live record.</span></div><a href={`/donors/${encodeURIComponent(id)}/meeting-brief`}>Prepare for Meeting</a></nav>}
    <section className="donor-snapshot-grid"><article className="snapshot-card"><p>Lifetime paid</p><strong>{money(paid)}</strong><span>{activities.length + legacyGifts.length} giving record{activities.length + legacyGifts.length === 1 ? "" : "s"}</span></article><article className="snapshot-card"><p>Most recent paid gift</p><strong>{mostRecent ? money(mostRecent.paid_cents ?? 0) : "—"}</strong><span>{mostRecent?.activity_date ? date(mostRecent.activity_date, profile.timezone) : "No paid gift recorded"}</span></article><article className="snapshot-card"><p>Open commitments</p><strong>{money(open)}</strong><span>From matched giving history</span></article><article className="snapshot-card"><p>Next action</p><strong>{next?.action || "None set"}</strong><span>{next?.due_at ? `Due ${date(next.due_at, profile.timezone)}` : "No dated reminder"}</span></article></section>
    <div className="relationship-grid"><main className="relationship-main">
      <section className="story-card ai-summary-card"><div className="card-heading"><div><p className="eyebrow">RELATIONSHIP SUMMARY · RULE-BASED</p><h2>{relationshipContext.summary ? "Current relationship context" : "No relationship summary yet"}</h2></div></div><p className="summary">{relationshipContext.summary || "Log a completed interaction to begin building a relationship summary from this household’s actual activity."}</p><div className="next-action"><div className="next-action-icon">→</div><div><p className="eyebrow">NEXT ACTION</p><h3>{next?.action || "No next action set"}</h3><p>{next?.reason || "Add a reminder when the next step becomes clear."}</p></div></div></section>
      <section className="story-card memory-card"><div className="card-heading"><div><p className="eyebrow">INSTITUTIONAL MEMORY</p><h2>{relationshipContext.memory ? "Recorded relationship context" : "No institutional memory recorded"}</h2></div></div>{relationshipContext.memory && <p className="summary">{relationshipContext.memory}</p>}</section>
      <section className="story-card timeline"><div className="card-heading"><div><p className="eyebrow">RELATIONSHIP HISTORY</p><h2>{interactionResult.results.length ? "Scheduled and completed interactions" : "No interactions recorded yet"}</h2></div></div>{interactionResult.results.length > 0 && <div className="timeline-list">{interactionResult.results.map((item) => { const scheduled = isScheduledActivity(item.source, item.occurred_at, item.created_at); return <article className={`timeline-item${scheduled ? " scheduled" : ""}`} key={item.id}><time><strong>{scheduled ? dateTime(item.occurred_at, profile.timezone) : date(item.occurred_at, profile.timezone)}</strong></time><span className="timeline-dot">•</span><div className="timeline-content"><div><h3>{item.summary.split("\n")[0]}</h3><span className="event-type">{scheduled ? `Scheduled ${item.type}` : item.type}</span></div><p>{item.summary.split("\n").slice(1).join("\n") || item.summary}</p></div></article>; })}</div>}</section>
      <section className="story-card giving-history"><div className="card-heading"><div><p className="eyebrow">GIVING HISTORY</p><h2>{activities.length || legacyGifts.length ? "Paid and committed support" : "No giving history imported yet"}</h2></div></div>{activities.map((item) => <article key={item.id}><time>{item.activity_date ? date(item.activity_date, profile.timezone) : "Date unavailable"}</time><div><strong>{item.description || item.item_type || "Giving activity"}</strong><small>{(item.paid_cents ?? 0) > 0 ? `${money(item.paid_cents ?? 0)} paid` : `${money(item.committed_cents ?? 0)} committed`}{(item.balance_cents ?? 0) > 0 ? ` · ${money(item.balance_cents ?? 0)} open` : ""}</small></div></article>)}</section>
    </main><aside className="relationship-rail"><section className="detail-card"><div className="detail-heading"><h2>Household</h2></div><dl className="at-a-glance"><div><dt>Members</dt><dd>{people || "Not supplied"}</dd></div><div><dt>JL reference</dt><dd>{donor.external_id || donor.donor_code || "Not supplied"}</dd></div><div><dt>Last meaningful contact</dt><dd>{completedInteractions[0] ? date(completedInteractions[0].occurred_at, profile.timezone) : "None recorded"}</dd></div></dl></section><section className="detail-card"><div className="detail-heading"><h2>Contact</h2></div><div className="facts contact-facts">{donor.email && <div className="fact"><label>Email</label><a href={`mailto:${donor.email}`}>{donor.email}</a></div>}{donor.phone && <div className="fact"><label>Mobile</label><a href={`tel:${donor.phone.replace(/\D/g, "")}`}>{donor.phone}</a></div>}{donor.home_phone && <div className="fact"><label>Home</label><a href={`tel:${donor.home_phone.replace(/\D/g, "")}`}>{donor.home_phone}</a></div>}{address.length > 0 && <div className="fact"><label>Mailing address</label>{address.map((line) => <p key={line}>{line}</p>)}</div>}</div></section></aside></div>
  </AppShell>;
}
